version: 1

sources:
  - name: utils
    database: QBM
    schema: dw_utils
    tables:
      - name: calendar
  
  - name: utils
    database: QBM
    schema: dw_utils
    tables:
      - name: countries

  - name: raw
    database: QBM
    schema: dw_raw
    tables:
      - name: daily_bonbast

  - name: raw
    database: QBM
    schema: dw_raw
    tables:
      - name: realtime_bonbast

  - name: raw
    database: QBM
    schema: dw_raw
    tables:
      - name: ai_predictions

  - name: raw
    database: QBM
    schema: dw_raw
    tables:
      - name: test_user_predicts

  - name: raw
    database: QBM
    schema: dw_raw
    tables:
      - name: daily_user_predicts






